### ISSUE TITLE
Synced::Model.synchronize should not modify  options argument, but clone the options and modify new object

### ISSUE THREAD

**Issue by Azdaroth** [BookingSync/synced#45]
Current behavior may lead to some pretty unexpected bugs, e.g. such code:

```
sync_options = { scope: Account.first }
Booking.synchronize(sync_options)
```

would raise `ArgumentError` when running more than one time, because the `sync_options` hash has been modified. Best to clone the options hash and work with new object.

**Comment by StoneFrog** [comment]
@Mandaryn I think this has been solved by #53 so can be closed.
