### ISSUE TITLE
Fix syncing process when synced_all_at column is not defined

### ISSUE THREAD

**Issue by Azdaroth** [BookingSync/synced#55]
It's a regression since 1.2.x version, `SyncedAllAtTimestampStrategy` assumes that `synced_all_at` is always defined, which is not always a case.

**Comment by Mandaryn** [comment]
i guess SyncedAllAtTimestampStrategy is assuming this correctly, why do you even want to use it if there is no `synced_all_at` in db? should use full strategy then

**Comment by Azdaroth** [comment]
So maybe `synced` should be smarter about resolving strategy? This will be the case for periods, seasons, rates tables and maybe more, would be nice to have it resolved correctly by default.

**Comment by Mandaryn** [comment]
the autoresolving of strategy was removed as it coupled too much code in the gem, switched to updated_since as default as it was more popular, but now `full` needs to be defined if defaults are not sufficient

**Comment by Azdaroth** [comment]
I think it may be worth introducing some coupling to make it more convenient: https://github.com/BookingSync/synced/blob/master/lib/synced/synchronizer.rb - we already have model class in initializer, so quite easy to check if `synced_all_at` or any other column exists.

**Comment by Mandaryn** [comment]
fell free to make a pr :trollface:

**Comment by Azdaroth** [comment]
:+1:

**Comment by Mandaryn** [comment]
nothing got proposed... sticking with explicit strategy setup
