### ISSUE TITLE
Investigate invalid updated_since sync when synced_all_at is nil

### ISSUE THREAD

**Issue by Fredar** [BookingSync/synced#56]
When doing `updated_since` sync with nil `synced_all_at` (after `reset_synced`) it should behave as full sync and remove everything not returned.

Currently does not remove anything.

**Comment by Mandaryn** [comment]
do we care about synced_all_at strategy? could we completely replace it by scoped timestamps?

**Comment by Fredar** [comment]
Indeed should be replaced, closing.
